### ISSUE TITLE
Ability to inject deps as an object?

### ISSUE THREAD

**Issue by Termina1** [angular/di.js#74]
Is this a good idea to create some annotation for class, so that injector would inject deps not as simple arguments, but as an object, i.e.:

```javascript
@Inject(A, B)
class MyClass {
  constructor(a, b) {
    this.a = a;
    this.b = b;
  }
}
```
instead do
```javascript
@Inject({a: A, b: B})
class MyClass {
  constructor({a, b}) {
    this.a = a;
    this.b = b;
  }
}
```

or something like that?

**Comment by petebacondarwin** [comment]
This idea relies on creating a relationship between the parameter names and the property names. But that this is a problem if the code is minified as the parameter names may change. The only thing that cannot change is the order of the parameters, which is what is currently being relied upon.
